import * as React  from "react"
import type {GetStaticProps,NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image';

import data from "../data.json";

import styles from '../styles/Home.module.css'
import { Note } from  '../types';

interface Props {
  notes : Note[];
}

const Home: NextPage<Props> = ({notes} ) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to los apuntes de Majo!
        </h1>

        <p className={styles.description}>
        Majo here! 👋🏻, realizo apuntes a mano
sobre las tecnologías más utilizadas.
        </p>

        <div className={styles.grid}>
          { notes.map( (note) => (
            <a key={note.id} className={styles.card} 
                  href={`/${note.id}`}>
              <h2>{note.title} &rarr;</h2>
              <p>{note.description}</p>
            </a>
          ) )}

          
        
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};


export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      notes: data
    },
    //revalidate:10,
  };
};

export default Home;